# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.head] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_head set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.body] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_body set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.right_arm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_arm set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.left_arm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_arm set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.right_leg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_leg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.left_leg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_leg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.bone] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.middle_door] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_middle_door set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.bone1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.blueprint.node.bone2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone2 set from storage animated_java:gu out