# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.blueprint.root] run return 0
execute if entity @s[tag=aj.blueprint.animation.animation_model_new.playing] run function animated_java:blueprint/animations/animation_model_new/zzz/on_tick
execute on passengers run rotate @s ~ ~