# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:blueprint rig_hash set value '8c183689f3ad240da6f3b62c1874ea0c02b0581607d97bc2c862109b99b483fd'
scoreboard objectives add aj.animation_model_new.frame dummy