# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '8c183689f3ad240da6f3b62c1874ea0c02b0581607d97bc2c862109b99b483fd'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack